---
quiet: true
skip-check:
  - CKV_AZURE_13 # Ensure App Service Authentication is set on Azure App Service
  - CKV_AZURE_17 # Ensure the web app has 'Client Certificates (Incoming client certificates)' set
  - CKV_AZURE_63 # Ensure that App service enables HTTP logging
  - CKV_AZURE_65 # Ensure that App service enables detailed error messages
  - CKV_AZURE_66 # Ensure that App service enables failed request tracing
  - CKV_AZURE_80 # Ensure that 'Net Framework' version is the latest, if used as a part of the web app
  - CKV_AZURE_88 # Ensure that App Services use Azure Files
  - CKV_AZURE_212 # Ensure App Service has a minimum number of instances for failover
  - CKV_AZURE_222 # Ensure that Azure Web App public network access is disabled
  - CKV_AZURE_225 # Ensure the App Service Plan is zone redundant
